apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: k3s
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KThreesControlPlaneTemplate
      name: k3s-control-plane
    machineInfrastructure:
      ref:
        kind: ElementalMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: k3s-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ElementalClusterTemplate
      name: k3s-cluster
  workers:
    machineDeployments:
      - class: k3s-default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: KThreesConfigTemplate
              name: k3s-default-worker-bootstrap
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: ElementalMachineTemplate
              name: k3s-default-worker

