apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KThreesControlPlaneTemplate
metadata:
  name: k3s-control-plane
spec:
  template:
    spec:
      version: "${k3sVersion}"
      machineTemplate:
        infrastructureRef:
          kind: ElementalMachineTemplate
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          name: k3s-control-plane

